"""добавил колонки дат

Revision ID: 547f190007bb
Revises: a6b1555fa651
Create Date: 2026-06-16 01:11:18.821044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547f190007bb'
down_revision: Union[str, None] = 'a6b1555fa651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('day_booking', sa.Date(), nullable=False))
    op.add_column('recordings', sa.Column('time_booking', sa.Time(), nullable=False))
    op.add_column('recordings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'created_at')
    op.drop_column('recordings', 'time_booking')
    op.drop_column('recordings', 'day_booking')
    # ### end Alembic commands ###
