"""empty message

Revision ID: a6b1555fa651
Revises: 
Create Date: 2026-06-15 17:22:49.098447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b1555fa651'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('third_name', sa.String(length=100), nullable=True),
    sa.Column('date_birth', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('ix_user_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('masters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_master_user_id', 'masters', ['user_id'], unique=False)
    op.create_table('recordings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recording_master_id', 'recordings', ['master_id'], unique=False)
    op.create_index('ix_recording_user_id', 'recordings', ['user_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photofeedbacks',
    sa.Column('photo', sa.String(length=500), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photofeedback_feedback_id', 'photofeedbacks', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photofeedback_feedback_id', table_name='photofeedbacks')
    op.drop_table('photofeedbacks')
    op.drop_table('feedbacks')
    op.drop_index('ix_recording_user_id', table_name='recordings')
    op.drop_index('ix_recording_master_id', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index('ix_master_user_id', table_name='masters')
    op.drop_table('masters')
    op.drop_index('ix_user_telegram_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
